//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVEWORDINFO
    {
        public string WORDID { get; set; }
        public string MESSAGE { get; set; }
        public string LEAVESTATE { get; set; }
        public Nullable<System.DateTime> LEAVETIME { get; set; }
        public string NICKNAME { get; set; }
    
        public virtual USERINFO USERINFO { get; set; }
    }
}
