//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERINFO()
        {
            this.LEAVEWORDINFO = new HashSet<LEAVEWORDINFO>();
            this.PICTUREINFO = new HashSet<PICTUREINFO>();
            this.SIGNINFO = new HashSet<SIGNINFO>();
        }
    
        public Nullable<decimal> USERID { get; set; }
        public string NICKNAME { get; set; }
        public string REALNAME { get; set; }
        public string PASSWORD { get; set; }
        public string MACADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVEWORDINFO> LEAVEWORDINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PICTUREINFO> PICTUREINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIGNINFO> SIGNINFO { get; set; }
    }
}
